### PR TITLE
Radar Chart Enhancement

### PR DESCRIPTION
**Pull request by DipParmar**

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
Hi Dip,

Thanks for attempting the pull request. Although I will close this particular one as this PR is requesting a merge of the wrong branch (this is attempting to merge in the v3.3.12 branch which is not yet released). But don't worry - ill just cancel it.

When you have committed your new branch with your code changes in (for example it may be 'patch-6' going by your current branch naming (but they can be named whatever you want)) when viewing your new branch with your code changes in on GitHub you then click on the 'Pull request' link (see screenshot attached).

screen shot 2018-07-03 at 17 51 54

This then raises a pull request asking for permission to merge your code changes 'up-stream' (which means the original repo) and you then get the opportunity to provide feedback and conversation about your merge request.

In Short, the end to to end:
1. Clone a Repo.
2. Create a new branch on your copy.
3. Make brilliant code changes.
4. Commit to your new branch.
5. Push to GitHub.
6. Click on 'Pull request'.
7. Provide detail to the author about what the code changes are, fixes, new features etc.
8. The author then assesses the pull request and code changes and may provide feedback or ask for changes (which then loops back to 3.)
9. Eventually when accepted the author clicks accept 'Merge pull request' and your changes are then merged into the upstream repo.

There is a good guide on this here: https://guides.github.com/introduction/flow/

Hope this makes sense! Don't worry if you get confused and would rather just do it as you did before thats TOTALLY fine, you are doing me a favour! I just though this may be quite useful to you as this process is the same to contribute to any Open Source project and it may be useful for you.

Once you contribute to an Open Source project it can get quite addictive - so watch out! But you learn loads!

**Comment by DipParmar** [comment]
Hi Jim,

Thanks for the guide lines.. It's really helpful..

I will do changes accordingly :)

Best Regards,
Dip Parmar

**Comment by DipParmar** [comment]
Hi Jim,

I will commit it by tomorrow, It's little more complex than I thought..
Really sorry for delay.

Regards
Dip Parmar

**Comment by jamesleesaunders** [comment]
Hi Dip,
Take as long as you like! There is no rush.
Please don’t put yourself out.

Sounds like it is an interesting puzzle!

**Comment by DipParmar** [comment]
Hi Jim,

Sorry for giving you update little late. 95% of the task is done.. chart is
complete but still figuring out a way to show legends....
I will update it by tonight and mail you...

Thanks and Regards,
Dip Parmar.

**Pull request closed without merging**
